version: "3"

services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    volumes:
      - /tmp:/tmp
    ports:
      - 3306
    networks:
      - network
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "dbuser"
      MYSQL_PASS: "dbpass"

    restart: always
  starbucks:
    image: spring-cashier
    platform: linux/amd64
    depends_on:
      - mysql
    volumes:
      - /tmp:/tmp
    ports:
      - 9090
    networks:
      - network
    environment:
      MYSQL_HOST: "mysql"
    restart: always
  lb:
    image: eeacms/haproxy
    platform: linux/amd64
    depends_on:
      - starbucks
    ports:
      - "80:5000"
      - "1936:1936"
    environment:
      BACKENDS: "starbucks"
      BACKENDS_PORT: "9090"
      DNS_ENABLED: "true"
      COOKIES_ENABLED: "false"
      LOG_LEVEL: "info"
    networks:
      - network

volumes:
  schemas:
    external: false

networks:
  network:
    driver: bridge